# Generated by Django 5.1.4 on 2026-09-15 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_score_type', models.CharField(blank=True, default='', max_length=30)),
                ('predicted_value', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, default='', help_text="e.g. 'added to portfolio'", max_length=200)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('actual_outcome_summary', models.CharField(blank=True, default='', max_length=300)),
                ('actual_outcome_metrics', models.JSONField(blank=True, default=dict)),
                ('outcome_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='catalog.product')),
                ('score_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_records', to='scoring.scorerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
