# Generated by Django 5.1.4 on 2026-09-15 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('ANALYZING', 'Analyzing'), ('WATCHLIST', 'Watchlist'), ('RECOMMENDED', 'Recommended'), ('AFFILIATION_PENDING', 'Affiliation pending'), ('AFFILIATED', 'Affiliated'), ('PORTFOLIO_ACTIVE', 'Portfolio active'), ('CREATIVE_PENDING', 'Creative pending'), ('READY_TO_PUBLISH', 'Ready to publish'), ('PUBLISHED', 'Published'), ('MONITORING', 'Monitoring'), ('OPTIMIZATION_REQUIRED', 'Optimization required'), ('SCALING', 'Scaling'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], default='DISCOVERED', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_item', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, choices=[('DISCOVERED', 'Discovered'), ('ANALYZING', 'Analyzing'), ('WATCHLIST', 'Watchlist'), ('RECOMMENDED', 'Recommended'), ('AFFILIATION_PENDING', 'Affiliation pending'), ('AFFILIATED', 'Affiliated'), ('PORTFOLIO_ACTIVE', 'Portfolio active'), ('CREATIVE_PENDING', 'Creative pending'), ('READY_TO_PUBLISH', 'Ready to publish'), ('PUBLISHED', 'Published'), ('MONITORING', 'Monitoring'), ('OPTIMIZATION_REQUIRED', 'Optimization required'), ('SCALING', 'Scaling'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], max_length=30)),
                ('to_state', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('ANALYZING', 'Analyzing'), ('WATCHLIST', 'Watchlist'), ('RECOMMENDED', 'Recommended'), ('AFFILIATION_PENDING', 'Affiliation pending'), ('AFFILIATED', 'Affiliated'), ('PORTFOLIO_ACTIVE', 'Portfolio active'), ('CREATIVE_PENDING', 'Creative pending'), ('READY_TO_PUBLISH', 'Ready to publish'), ('PUBLISHED', 'Published'), ('MONITORING', 'Monitoring'), ('OPTIMIZATION_REQUIRED', 'Optimization required'), ('SCALING', 'Scaling'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('actor', models.CharField(blank=True, default='', help_text='Who/what triggered this transition', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='portfolio.portfolioitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
