# Generated by Django 5.1.4 on 2026-09-15 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('integration_status', models.CharField(choices=[('live', 'Live'), ('not_implemented', 'Not implemented')], default='not_implemented', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('seller_name', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.FloatField(blank=True, null=True)),
                ('previous_price', models.FloatField(blank=True, null=True)),
                ('discount_pct', models.FloatField(blank=True, null=True)),
                ('commission_pct', models.FloatField(blank=True, null=True)),
                ('available', models.BooleanField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('orders_count', models.IntegerField(blank=True, null=True)),
                ('promotions', models.JSONField(blank=True, default=list)),
                ('coupons', models.JSONField(blank=True, default=list)),
                ('affiliate_program_info', models.JSONField(blank=True, default=dict)),
                ('original_url', models.URLField(blank=True, default='', max_length=1000)),
                ('affiliate_url', models.URLField(blank=True, default='', max_length=1000)),
                ('images', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(help_text="Where this row came from, e.g. 'mercado_livre_search'", max_length=100)),
                ('reliability', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('collected_at', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Raw payload from the source, for audit/debug.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.marketplace')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['marketplace', 'category'], name='catalog_pro_marketp_5d6090_idx'), models.Index(fields=['collected_at'], name='catalog_pro_collect_d07f9b_idx')],
                'constraints': [models.UniqueConstraint(fields=('marketplace', 'external_id'), name='unique_product_per_marketplace')],
            },
        ),
    ]
