# Generated by Django 5.1.4 on 2026-09-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(default='affiliate', max_length=20)),
                ('scope', models.CharField(default='national,international', max_length=100)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='catalog.marketplace')),
            ],
        ),
    ]
