# Generated by Django 5.1.4 on 2026-09-15 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('copy', 'Copy'), ('image', 'Image'), ('video', 'Video'), ('voice', 'Voice / narration'), ('edit', 'Edit'), ('approval', 'Approval'), ('publication', 'Publication')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=10)),
                ('external_ref', models.CharField(blank=True, default='', help_text='Future AI Studio asset id', max_length=200)),
                ('updated_by', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_assets', to='portfolio.portfolioitem')),
            ],
            options={
                'ordering': ['portfolio_item_id', 'asset_type'],
                'constraints': [models.UniqueConstraint(fields=('portfolio_item', 'asset_type'), name='unique_asset_per_stage')],
            },
        ),
    ]
