# Generated by Django 5.1.4 on 2026-09-15 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('heat', 'Heat Score'), ('opportunity', 'Opportunity Score'), ('producer_momentum', 'Producer Momentum Score'), ('creative_saturation', 'Creative Saturation Score'), ('portfolio', 'Portfolio Score'), ('creative', 'Creative Score')], max_length=30)),
                ('version', models.CharField(help_text="Formula version, e.g. 'v1'", max_length=20)),
                ('inputs', models.JSONField(default=dict)),
                ('weights', models.JSONField(default=dict)),
                ('result', models.FloatField()),
                ('reliability', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Downgraded when required inputs were missing.', max_length=10)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='catalog.product')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1)),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('score_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='scoring.scorerecord')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='scorerecord',
            index=models.Index(fields=['product', 'score_type', '-computed_at'], name='scoring_sco_product_723e65_idx'),
        ),
    ]
